# Generated by Django 5.2 on 2025-04-03 15:45

import django.utils.timezone
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Producto')),
                ('category', models.CharField(choices=[('Alimentos', 'Alimentos'), ('Electrónica', 'Electrónica'), ('Ropa', 'Ropa'), ('Hogar', 'Hogar'), ('Otro', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código Único')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[products.models.validate_sale_price], verbose_name='Precio de Venta')),
                ('stock_quantity', models.PositiveIntegerField(verbose_name='Cantidad en Stock')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrada')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad')),
            ],
        ),
    ]
