name: Build and deploy Python app to Azure Web App - backinventary1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # usa la versión que necesites

      - name: Clean node_modules and lockfile  # 🔧 Paso agregado para evitar error de rollup
        run: |
          cd frontend/client
          rm -rf node_modules package-lock.json

      - name: Install frontend dependencies and build
        run: |
          cd frontend/client
          npm install --legacy-peer-deps
          npm run build


      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Install backend dependencies
        run: |
          source venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Collect static files
        run: |
          source venv/bin/activate
          cd backend
          python manage.py collectstatic --noinput

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip backend staticfiles  # incluye backend y staticfiles

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FC880F7BA65F4D47B9358D9D87D49576 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4B97D47D9A4141F69A274612D8B2DAD5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_72311D2DE9EE488A86789116A718CD45 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'backinventary1'
          slot-name: 'Production'
          package: .
